name: Deploy API

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Remove gitignore file
        run: |
          rm .gitignore
          ls -a
      - name: Create ENV for PRD
        run: |
          touch production.env
          echo PORT=${{ secrets.API_PORT }} >> production.env
          echo HOST=${{ secrets.API_HOST }} >> production.env
          echo FRONT_URL=${{ secrets.API_FRONT_URL }} >> production.env
          echo DB_URL=${{ secrets.API_DB_URL }} >> production.env
          echo DB_USER=${{ secrets.API_DB_USER }} >> production.env
          echo DB_PWD=${{ secrets.API_DB_PWD }} >> production.env
          echo JWT_SECRET=${{ secrets.API_JWT_SECRET }} >> production.env
          echo JWT_MAX_EXP_TIME=${{ secrets.API_JWT_MAX_EXP_TIME }} >> production.env
          echo EMAIL_USER=${{ secrets.API_EMAIL_USER }} >> production.env
          echo EMAIL_PWD=${{ secrets.API_EMAIL_PWD }} >> production.env
          cat production.env
      - name: Commit changes
        run: |
          git config --global user.name ${{ secrets.API_USER_NAME }}
          git config --global user.email ${{ secrets.API_USER_EMAIL }}
          git add .
          git commit -m "Add env file"
      - uses: akhileshns/heroku-deploy@v3.3.6 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.API_APP_NAME }}
          heroku_email: ${{ secrets.API_USER_EMAIL }}